### ISSUE TITLE
ValueError: invalid null reference in 'Session_sendToTarget'

### ISSUE THREAD

**Issue by umaaaaaaaaa** [rinleit/quickfix-sample-python#6]
Hi! When I run the application, I get an error.
Before running the fix.Session.sendToTarget(message, self.sessionID), I've printed the self.sessionID and I've got None value. When does the sessionID changes after assigning sessionID=None in Application class? 
I'm getting the following error:

Traceback (most recent call last):
  File "client.py", line 30, in <module>
    main(args.file_name)
  File "client.py", line 17, in main
    application.run()
  File "/home/ubuntu/test/quickfix-python-samples/initiator/application.py", line 89, in run
    self.put_new_order()
  File "/home/ubuntu/test/quickfix-python-samples/initiator/application.py", line 82, in put_new_order
    fix.Session.sendToTarget(message, self.sessionID)
ValueError: invalid null reference in method 'Session_sendToTarget', argument 2 of type 'FIX::SessionID const &'
Segmentation fault (core dumped)

**Comment by umaaaaaaaaa** [comment]
Sorry, I forgot, that I've changed your class Application. Now it looks like this:
class Application(fix.Application):
    """FIX Application"""
    execID = 0
    sessionID=None
Otherwise I get AttributeError: 'Application' object has no attribute 'sessionID'

**Comment by rinlevan** [comment]
Hi @umaaaaaaaaa, If you want to send a msg to test a new order. First, You have to start with the acceptor model. You can run code in the acceptor folder. Let's keep the source code original. The **sessionID** will get a value when the acceptor has a connection to the client (Initiator).
