### ISSUE TITLE
Getting error while install quickfix

### ISSUE THREAD

**Issue by Umair-A** [rinleit/quickfix-sample-python#9]
![Screenshot 2024-02-26 153107](https://github.com/rinleit/quickfix-python-samples/assets/90497270/399f65e1-2c12-49a0-8183-d7a15019621e)

I am getting errors while building wheels for the quick-fix installation. I have attached a screenshot please have a look.

**Comment by rinlevan** [comment]
@Umair-A Try installing as administrator or install another version of MSVC++, however you should build a quickfix on linux environment which will be easy to install and run better than on windows environment.

**Comment by Umair-A** [comment]
I have tried to install it through the administrator but the error is the same I don't have a Linux system how can I install it on the windows system as previously I have installed it by adding these whl file but these are available anymore how can we do that. 
https://download.lfd.uci.edu/pythonlibs/archived/cp27/quickfix-1.14.3-cp27-none-win32.whl

**Comment by rinlevan** [comment]
You can install WSL (Windows Subsystem for Linux) and setup quickfix on it. I recommend you install on linux environment. 
1. Install WSL here: https://learn.microsoft.com/en-us/windows/wsl/install
2. Run: `sudo apt-get update` after that Run `sudo apt install python3-pip`
3. Just install: `pip install quickfix==1.15.1`
![ksnip_20240301-221439](https://github.com/rinleit/quickfix-python-samples/assets/26803121/cac80d42-48c7-40c6-8de8-85f62dca0918)
Screen shot on my pc

**Comment by Umair-A** [comment]
Yeah, it's done Thanks

**Comment by Umair-A** [comment]
Yeah, it's done thanks
